# Copyright 2023 Contributors to the EdgeNet project.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: federation.edgenet.io/v1alpha1
kind: Cluster
metadata:
  name: workload01
  namespace: test
  labels:
    edge-net.io/city: Paris
spec:
  uid: c79ef63e-d050-43a9-852b-51d5161c68cf
  role: Workload
  server: 192.168.64.8:8443
  visibility: Public
  secretName: fedmanager-workload01
  enabled: true
---
apiVersion: federation.edgenet.io/v1alpha1
kind: Cluster
metadata:
  name: workload02
  namespace: test
  labels:
    edge-net.io/city: Izmir
spec:
  uid: e3e7882a-5436-417d-9ffa-056a700c6433
  role: Workload
  server: 192.168.64.9:8443
  visibility: Public
  secretName: fedmanager-workload02
  enabled: true
